/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StructureIndexRouteImport } from './routes/structure/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us/index'
import { Route as NewsPostIdIndexRouteImport } from './routes/news/$postId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureIndexRoute = StructureIndexRouteImport.update({
  id: '/structure/',
  path: '/structure/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsPostIdIndexRoute = NewsPostIdIndexRouteImport.update({
  id: '/news/$postId/',
  path: '/news/$postId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsIndexRoute
  '/contact': typeof ContactIndexRoute
  '/news': typeof NewsIndexRoute
  '/structure': typeof StructureIndexRoute
  '/news/$postId': typeof NewsPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsIndexRoute
  '/contact': typeof ContactIndexRoute
  '/news': typeof NewsIndexRoute
  '/structure': typeof StructureIndexRoute
  '/news/$postId': typeof NewsPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/news/': typeof NewsIndexRoute
  '/structure/': typeof StructureIndexRoute
  '/news/$postId/': typeof NewsPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact'
    | '/news'
    | '/structure'
    | '/news/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about-us' | '/contact' | '/news' | '/structure' | '/news/$postId'
  id:
    | '__root__'
    | '/'
    | '/about-us/'
    | '/contact/'
    | '/news/'
    | '/structure/'
    | '/news/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  StructureIndexRoute: typeof StructureIndexRoute
  NewsPostIdIndexRoute: typeof NewsPostIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure/': {
      id: '/structure/'
      path: '/structure'
      fullPath: '/structure'
      preLoaderRoute: typeof StructureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$postId/': {
      id: '/news/$postId/'
      path: '/news/$postId'
      fullPath: '/news/$postId'
      preLoaderRoute: typeof NewsPostIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  StructureIndexRoute: StructureIndexRoute,
  NewsPostIdIndexRoute: NewsPostIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
